apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: post-like-handler
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ascreciu/post-like-handler:latest
          ports:
            - containerPort: 8080
          env:
            - name: BROKER_URL
              value: "http://soa-rabbitmq-cluster-broker.default.svc.cluster.local"
