apiVersion: v1
kind: Service
metadata:
  name: "notification-service"
  labels:
    {{- include "notifications-service-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "notifications-service-chart.selectorLabels" . | nindent 4 }}
